set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(OHOS_NATIVE_BIN "/data/service/hnp/bin")
set(OHOS_SYSROOT "/data/service/hnp/ohos-sdk.org/ohos-sdk_26.0.0.18/ohos/native/sysroot")

set(CMAKE_C_COMPILER "${OHOS_NATIVE_BIN}/clang")
set(CMAKE_CXX_COMPILER "${OHOS_NATIVE_BIN}/clang++")
set(CMAKE_AR "${OHOS_NATIVE_BIN}/llvm-ar" CACHE FILEPATH "ar" FORCE)
set(CMAKE_RANLIB "${OHOS_NATIVE_BIN}/llvm-ranlib" CACHE FILEPATH "ranlib" FORCE)

set(CMAKE_C_COMPILER_TARGET "aarch64-linux-ohos")
set(CMAKE_CXX_COMPILER_TARGET "aarch64-linux-ohos")

set(CMAKE_SYSROOT "${OHOS_SYSROOT}")

set(CMAKE_MAKE_PROGRAM "${OHOS_NATIVE_BIN}/ninja" CACHE FILEPATH "ninja" FORCE)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__MUSL__" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__MUSL__" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
